name: Notifier

on:
  push:
    branches: [ main ]

jobs:

  messageWhatsApp:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
      - name: send custom message
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "New Pushes are incoming"
