name: Pull Request Notifier

on:
  pull_request:
    branches: [ main ]

jobs:

  messageTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: send custom message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "New Pull request in ${{ github.repository }} are incoming"
