name: JUnit Jacoco

on:
  push:
    branches:
      - "main"

jobs:
  unit-covarege-tests:
    name: Unit And Coverage Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '18'
      - name: Run tests
        run: |
          mvn clean verify
